version: "3"

tasks:
  build:
    cmds:
      - ./scripts/build-app-bundle.sh

  start:macos:
    env:
      VERSION: 9.9.9
    cmds:
      - ./scripts/build-app-bundle.sh
      - pkill awayuki || true
      - sleep 1
      - open ./build/Awayuki.app
